"""add billing events and vendor access audit

Revision ID: 1e214cde33a5
Revises: db3a11b0b611
Create Date: 2026-02-14 13:47:51.307852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e214cde33a5'
down_revision: Union[str, Sequence[str], None] = 'db3a11b0b611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billingevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mp_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('normalized', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billingevent_mp_event_id'), 'billingevent', ['mp_event_id'], unique=False)
    op.create_table('vendoraccessaudit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendoraccessaudit')
    op.drop_index(op.f('ix_billingevent_mp_event_id'), table_name='billingevent')
    op.drop_table('billingevent')
    # ### end Alembic commands ###
