"""add iam models and parent id

Revision ID: 46049fc57822
Revises: 76b028d8998f
Create Date: 2026-02-14 10:27:32.013152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46049fc57822'
down_revision: Union[str, Sequence[str], None] = '76b028d8998f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iampolicy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iampolicy_name'), 'iampolicy', ['name'], unique=True)
    op.create_table('useriampolicylink',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['iampolicy.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'policy_id')
    )
    op.execute('DROP INDEX IF EXISTS checkpoints_thread_id_idx')
    op.execute('DROP TABLE IF EXISTS checkpoints')
    op.execute('DROP INDEX IF EXISTS checkpoint_blobs_thread_id_idx')
    op.execute('DROP TABLE IF EXISTS checkpoint_blobs')
    op.execute('DROP INDEX IF EXISTS checkpoint_writes_thread_id_idx')
    op.execute('DROP TABLE IF EXISTS checkpoint_writes')
    op.execute('DROP TABLE IF EXISTS checkpoint_migrations')
    op.add_column('user', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_parent_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'parent_id')
    op.drop_table('useriampolicylink')
    op.drop_index(op.f('ix_iampolicy_name'), table_name='iampolicy')
    op.drop_table('iampolicy')
    # ### end Alembic commands ###
