"""implement_b2b2c_models

Revision ID: 4886fd92b836
Revises: e5a91a5085f1
Create Date: 2026-02-10 18:37:17.227313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4886fd92b836'
down_revision: Union[str, Sequence[str], None] = 'e5a91a5085f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean up data to avoid constraint violations during major refactor
    # We are changing the fundamental data model (B2B2C), so existing data is incompatible.
    op.execute("TRUNCATE TABLE product, invoice, ticket, appointment RESTART IDENTITY CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.add_column('appointment', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('appointment', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('appointment_client_id_fkey'), 'appointment', type_='foreignkey')
    op.create_foreign_key('appointment_customer_id_fkey', 'appointment', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key('appointment_user_id_fkey', 'appointment', 'user', ['user_id'], ['id'])
    op.drop_column('appointment', 'client_id')
    op.add_column('auditlog', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('auditlog_user_id_fkey', 'auditlog', 'user', ['user_id'], ['id'])
    op.add_column('invoice', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('invoice', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('invoice_client_id_fkey'), 'invoice', type_='foreignkey')
    op.create_foreign_key('invoice_user_id_fkey', 'invoice', 'user', ['user_id'], ['id'])
    op.create_foreign_key('invoice_customer_id_fkey', 'invoice', 'customer', ['customer_id'], ['id'])
    op.drop_column('invoice', 'client_id')
    op.add_column('product', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('product_user_id_fkey', 'product', 'user', ['user_id'], ['id'])
    op.add_column('ticket', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('ticket', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('ticket_client_id_fkey'), 'ticket', type_='foreignkey')
    op.create_foreign_key('ticket_user_id_fkey', 'ticket', 'user', ['user_id'], ['id'])
    op.create_foreign_key('ticket_customer_id_fkey', 'ticket', 'customer', ['customer_id'], ['id'])
    op.drop_column('ticket', 'client_id')
    op.add_column('user', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    op.add_column('ticket', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('ticket_user_id_fkey', 'ticket', type_='foreignkey')
    op.drop_constraint('ticket_customer_id_fkey', 'ticket', type_='foreignkey')
    op.create_foreign_key(op.f('ticket_client_id_fkey'), 'ticket', 'user', ['client_id'], ['id'])
    op.drop_column('ticket', 'user_id')
    op.drop_column('ticket', 'customer_id')
    op.drop_constraint('product_user_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'user_id')
    op.add_column('invoice', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('invoice_user_id_fkey', 'invoice', type_='foreignkey')
    op.drop_constraint('invoice_customer_id_fkey', 'invoice', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_client_id_fkey'), 'invoice', 'user', ['client_id'], ['id'])
    op.drop_column('invoice', 'user_id')
    op.drop_column('invoice', 'customer_id')
    op.drop_constraint('auditlog_user_id_fkey', 'auditlog', type_='foreignkey')
    op.drop_column('auditlog', 'user_id')
    op.add_column('appointment', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('appointment_user_id_fkey', 'appointment', type_='foreignkey')
    op.drop_constraint('appointment_customer_id_fkey', 'appointment', type_='foreignkey')
    op.create_foreign_key(op.f('appointment_client_id_fkey'), 'appointment', 'user', ['client_id'], ['id'])
    op.drop_column('appointment', 'user_id')
    op.drop_column('appointment', 'customer_id')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
