"""add vendor telegram integration

Revision ID: 5ef30cbd5f80
Revises: 1e214cde33a5
Create Date: 2026-02-15 20:13:53.723027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ef30cbd5f80'
down_revision: Union[str, Sequence[str], None] = '1e214cde33a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendortelegramintegration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('bot_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bot_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_index(op.f('ix_vendortelegramintegration_bot_username'), 'vendortelegramintegration', ['bot_username'], unique=False)
    op.create_index(op.f('ix_vendortelegramintegration_webhook_secret'), 'vendortelegramintegration', ['webhook_secret'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendortelegramintegration_webhook_secret'), table_name='vendortelegramintegration')
    op.drop_index(op.f('ix_vendortelegramintegration_bot_username'), table_name='vendortelegramintegration')
    op.drop_table('vendortelegramintegration')
    # ### end Alembic commands ###
