"""update_product_model

Revision ID: e5a91a5085f1
Revises: 0b43fb768579
Create Date: 2026-02-10 13:11:51.501479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5a91a5085f1'
down_revision: Union[str, Sequence[str], None] = '0b43fb768579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Safe drops for LangGraph tables/indexes using raw SQL
    op.execute("DROP INDEX IF EXISTS checkpoint_blobs_thread_id_idx")
    op.execute("DROP TABLE IF EXISTS checkpoint_blobs")
    op.execute("DROP INDEX IF EXISTS checkpoint_writes_thread_id_idx")
    op.execute("DROP TABLE IF EXISTS checkpoint_writes")
    op.execute("DROP TABLE IF EXISTS checkpoint_migrations")
    op.execute("DROP INDEX IF EXISTS checkpoints_thread_id_idx")
    op.execute("DROP TABLE IF EXISTS checkpoints")
    op.add_column('product', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('product', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('product', sa.Column('min_stock_threshold', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('sla', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('product', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('product', 'sla')
    op.drop_column('product', 'min_stock_threshold')
    op.drop_column('product', 'status')
    op.drop_column('product', 'type')
    # ### end Alembic commands ###
