"""add mfa fields to user

Revision ID: e93ca5cafd30
Revises: f0e869ff87b7
Create Date: 2026-02-11 13:30:43.195080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e93ca5cafd30'
down_revision: Union[str, Sequence[str], None] = 'f0e869ff87b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtoken', sa.Column('is_revoked', sa.Boolean(), nullable=False, server_default="false"))
    op.add_column('refreshtoken', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('role', sa.Column('permissions', sa.JSON(), nullable=True))
    op.add_column('role', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('role', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default="false"))
    op.add_column('user', sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'totp_secret')
    op.drop_column('user', 'mfa_enabled')
    op.alter_column('role', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('role', 'created_at')
    op.drop_column('role', 'permissions')
    op.drop_column('refreshtoken', 'created_at')
    op.drop_column('refreshtoken', 'is_revoked')
    # ### end Alembic commands ###
